### ISSUE TITLE
Metadatakvalitets-tjenesten gir 100% der det ikke skal være 100%

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-metadata-quality-service#19]
Dette gjelder prod:
Ref: 
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/41aef848-f996-4b71-8b73-c5ef897b0a60)

"
som logges litt upraktisk som en og en linje, istedet for en enkelt errordump
3:31
no.fdk.exception.NotFoundException: 404 NOT_FOUND "Could not find any entries with entity URI: https://dataservice-catalog.fellesdatakatalog.digdir.no/data-services/5f461df34e59ff37b6caea10"
	at no.fdk.service.AssessmentService.getEntityAssessment(AssessmentService.java:66) ~[classes!/:1.0.0]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
ser ut som den dukker opp for ca alt som metadata-quality leser"

Mulig feil fra GCP:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/20b1591c-2382-4433-9aba-a81898a768f5)
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/7c4bf3a4-51fe-4438-b4ff-38e5211d38ed)
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/ff3c7b7a-5e5d-46e3-9daa-4bbed772bed2)

**Comment by shenluna** [comment]
Testet og verifisert i staging og prod.
