### ISSUE TITLE
Metadatakvalitet - klikkbar navn på datasettene

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/fdk-metadata-quality-service#21]
Ønske om å ha klkkbare navn på metadatakvalitetsiden som fører til datasettene det gjelder.

![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/7ef67d40-d1dc-42f6-b5a6-eb0bc420417c)

**Comment by azaxarov** [comment]
Det ser ut som vi allerede har en måte å navigere tilbake til datasettet. Hva gjør vi med det @lillelars @shenluna ?

![Screenshot 2021-05-18 at 12.18.08.png](https://images.zenhubusercontent.com/5d402ba1ca7b4e0001322ad3/5d4e04f0-18c4-46d1-80e8-cb837cb0d33a)

**Comment by shenluna** [comment]
@azaxarov Jeg tenker det er fint. Så lenge det er en måte å komme seg enkelt tilbake til datasettet så holder det :)
Jeg lukker saken
