### ISSUE TITLE
Lenke tilbake til detaljevisning av datasett

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-metadata-quality-service#28]
Denne mangler på metadatakvalitetssiden:
![image](https://user-images.githubusercontent.com/39513382/109312082-e500a280-7846-11eb-8aef-fc30d58514a1.png)

Ref f.eks dette datasettet:
https://data.norge.no/organizations/971526920/datasets/15d63821-210d-4cdb-be62-927b3c7f1cb6

Se design:

https://www.figma.com/proto/LNZcZ406JNnINt6phaec5b/Companies?node-id=31%3A11039&viewport=636%2C182%2C0.5400004982948303&scaling=min-zoom

**Comment by jeffreiffers** [comment]
Denne fikser også denne https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/198

**Comment by shenluna** [comment]
Testet i staging
![image](https://user-images.githubusercontent.com/73637969/109496567-1d93bc80-7a91-11eb-94e5-c2b41723f891.png)

**Comment by shenluna** [comment]
Testet i staging
![image](https://user-images.githubusercontent.com/73637969/109497064-ce01c080-7a91-11eb-9d45-c95940e0845f.png)

**Comment by lillelars** [comment]
@oyvindis var det Informasjonsforvaltning/fdk-issue-tracker#198 du tok tak i ? Og da er du klar over at denne fikser det issuet?

**Comment by shenluna** [comment]
Verifisert i prod
