### ISSUE TITLE
Feil validering på metadatakvalitet IANA formater distribusjon

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-metadata-quality-service#30]
F.eks gir dette datasettet ingen formater på godkjent IANA mediatype:
https://data.norge.no/datasets/15d63821-210d-4cdb-be62-927b3c7f1cb6

Men metadatakvaliteten gir 100% på interoperabilitet likevel:
https://data.norge.no/organizations/971526920/datasets/15d63821-210d-4cdb-be62-927b3c7f1cb6

![image](https://user-images.githubusercontent.com/39513382/109623021-06aaa400-7b3d-11eb-86f1-a49de8defb58.png)

**Comment by shenluna** [comment]
Testet og verifisert.
