### ISSUE TITLE
Metadata-service: NAP-filter

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-metadata-quality-service#41]
- [x] Mulig å hente oppsummert catalogRating kun basert på NAP-entities
- [x] Mulig å hente liste `entities` filtrert på NAP

**Comment by shenluna** [comment]
NAP-filteret svarer med tom liste
![image](https://user-images.githubusercontent.com/73637969/115859125-0c7f8000-a430-11eb-8a5a-641865b8a522.png)
![image](https://user-images.githubusercontent.com/73637969/115859176-199c6f00-a430-11eb-8a07-4107644aaf6e.png)

**Comment by shenluna** [comment]
Flytter saken til TO DO da den for øyeblikket er blokkert av et annet issue

**Comment by shenluna** [comment]
Testet og verifisert OK
![image](https://user-images.githubusercontent.com/73637969/117412995-bb828800-af15-11eb-8e3c-3cafef4a8441.png)
